/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KitRouteImport } from './routes/_kit'
import { Route as KitIndexRouteImport } from './routes/_kit/index'
import { Route as KitTokensRouteImport } from './routes/_kit/tokens'
import { Route as KitComponentsIndexRouteImport } from './routes/_kit/components/index'
import { Route as KitComponentsIdRouteImport } from './routes/_kit/components/$id'
import { Route as KitFeaturesIndexRouteImport } from './routes/_kit/features/index'
import { Route as KitFeaturesIdRouteImport } from './routes/_kit/features/$id'
import { Route as KitPagesIndexRouteImport } from './routes/_kit/pages/index'
import { Route as KitPagesSlugRouteImport } from './routes/_kit/pages/$slug'
import { Route as KitPatternsIndexRouteImport } from './routes/_kit/patterns/index'
import { Route as KitPatternsIdRouteImport } from './routes/_kit/patterns/$id'
import { Route as KitPrimitivesIndexRouteImport } from './routes/_kit/primitives/index'
import { Route as KitPrimitivesIdRouteImport } from './routes/_kit/primitives/$id'

const KitRoute = KitRouteImport.update({
  id: '/_kit',
  getParentRoute: () => rootRouteImport,
} as any)
const KitIndexRoute = KitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KitRoute,
} as any)
const KitTokensRoute = KitTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => KitRoute,
} as any)
const KitComponentsIndexRoute = KitComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => KitRoute,
} as any)
const KitComponentsIdRoute = KitComponentsIdRouteImport.update({
  id: '/components/$id',
  path: '/components/$id',
  getParentRoute: () => KitRoute,
} as any)
const KitFeaturesIndexRoute = KitFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => KitRoute,
} as any)
const KitFeaturesIdRoute = KitFeaturesIdRouteImport.update({
  id: '/features/$id',
  path: '/features/$id',
  getParentRoute: () => KitRoute,
} as any)
const KitPagesIndexRoute = KitPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => KitRoute,
} as any)
const KitPagesSlugRoute = KitPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => KitRoute,
} as any)
const KitPatternsIndexRoute = KitPatternsIndexRouteImport.update({
  id: '/patterns/',
  path: '/patterns/',
  getParentRoute: () => KitRoute,
} as any)
const KitPatternsIdRoute = KitPatternsIdRouteImport.update({
  id: '/patterns/$id',
  path: '/patterns/$id',
  getParentRoute: () => KitRoute,
} as any)
const KitPrimitivesIndexRoute = KitPrimitivesIndexRouteImport.update({
  id: '/primitives/',
  path: '/primitives/',
  getParentRoute: () => KitRoute,
} as any)
const KitPrimitivesIdRoute = KitPrimitivesIdRouteImport.update({
  id: '/primitives/$id',
  path: '/primitives/$id',
  getParentRoute: () => KitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof KitIndexRoute
  '/tokens': typeof KitTokensRoute
  '/components/$id': typeof KitComponentsIdRoute
  '/features/$id': typeof KitFeaturesIdRoute
  '/pages/$slug': typeof KitPagesSlugRoute
  '/patterns/$id': typeof KitPatternsIdRoute
  '/primitives/$id': typeof KitPrimitivesIdRoute
  '/components/': typeof KitComponentsIndexRoute
  '/features/': typeof KitFeaturesIndexRoute
  '/pages/': typeof KitPagesIndexRoute
  '/patterns/': typeof KitPatternsIndexRoute
  '/primitives/': typeof KitPrimitivesIndexRoute
}
export interface FileRoutesByTo {
  '/tokens': typeof KitTokensRoute
  '/': typeof KitIndexRoute
  '/components/$id': typeof KitComponentsIdRoute
  '/features/$id': typeof KitFeaturesIdRoute
  '/pages/$slug': typeof KitPagesSlugRoute
  '/patterns/$id': typeof KitPatternsIdRoute
  '/primitives/$id': typeof KitPrimitivesIdRoute
  '/components': typeof KitComponentsIndexRoute
  '/features': typeof KitFeaturesIndexRoute
  '/pages': typeof KitPagesIndexRoute
  '/patterns': typeof KitPatternsIndexRoute
  '/primitives': typeof KitPrimitivesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_kit': typeof KitRouteWithChildren
  '/_kit/tokens': typeof KitTokensRoute
  '/_kit/': typeof KitIndexRoute
  '/_kit/components/$id': typeof KitComponentsIdRoute
  '/_kit/features/$id': typeof KitFeaturesIdRoute
  '/_kit/pages/$slug': typeof KitPagesSlugRoute
  '/_kit/patterns/$id': typeof KitPatternsIdRoute
  '/_kit/primitives/$id': typeof KitPrimitivesIdRoute
  '/_kit/components/': typeof KitComponentsIndexRoute
  '/_kit/features/': typeof KitFeaturesIndexRoute
  '/_kit/pages/': typeof KitPagesIndexRoute
  '/_kit/patterns/': typeof KitPatternsIndexRoute
  '/_kit/primitives/': typeof KitPrimitivesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tokens'
    | '/components/$id'
    | '/features/$id'
    | '/pages/$slug'
    | '/patterns/$id'
    | '/primitives/$id'
    | '/components/'
    | '/features/'
    | '/pages/'
    | '/patterns/'
    | '/primitives/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/tokens'
    | '/'
    | '/components/$id'
    | '/features/$id'
    | '/pages/$slug'
    | '/patterns/$id'
    | '/primitives/$id'
    | '/components'
    | '/features'
    | '/pages'
    | '/patterns'
    | '/primitives'
  id:
    | '__root__'
    | '/_kit'
    | '/_kit/tokens'
    | '/_kit/'
    | '/_kit/components/$id'
    | '/_kit/features/$id'
    | '/_kit/pages/$slug'
    | '/_kit/patterns/$id'
    | '/_kit/primitives/$id'
    | '/_kit/components/'
    | '/_kit/features/'
    | '/_kit/pages/'
    | '/_kit/patterns/'
    | '/_kit/primitives/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  KitRoute: typeof KitRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_kit': {
      id: '/_kit'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_kit/': {
      id: '/_kit/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof KitIndexRouteImport
      parentRoute: typeof KitRoute
    }
    '/_kit/tokens': {
      id: '/_kit/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof KitTokensRouteImport
      parentRoute: typeof KitRoute
    }
    '/_kit/components/': {
      id: '/_kit/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof KitComponentsIndexRouteImport
      parentRoute: typeof KitRoute
    }
    '/_kit/components/$id': {
      id: '/_kit/components/$id'
      path: '/components/$id'
      fullPath: '/components/$id'
      preLoaderRoute: typeof KitComponentsIdRouteImport
      parentRoute: typeof KitRoute
    }
    '/_kit/features/': {
      id: '/_kit/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof KitFeaturesIndexRouteImport
      parentRoute: typeof KitRoute
    }
    '/_kit/features/$id': {
      id: '/_kit/features/$id'
      path: '/features/$id'
      fullPath: '/features/$id'
      preLoaderRoute: typeof KitFeaturesIdRouteImport
      parentRoute: typeof KitRoute
    }
    '/_kit/pages/': {
      id: '/_kit/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof KitPagesIndexRouteImport
      parentRoute: typeof KitRoute
    }
    '/_kit/pages/$slug': {
      id: '/_kit/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof KitPagesSlugRouteImport
      parentRoute: typeof KitRoute
    }
    '/_kit/patterns/': {
      id: '/_kit/patterns/'
      path: '/patterns'
      fullPath: '/patterns/'
      preLoaderRoute: typeof KitPatternsIndexRouteImport
      parentRoute: typeof KitRoute
    }
    '/_kit/patterns/$id': {
      id: '/_kit/patterns/$id'
      path: '/patterns/$id'
      fullPath: '/patterns/$id'
      preLoaderRoute: typeof KitPatternsIdRouteImport
      parentRoute: typeof KitRoute
    }
    '/_kit/primitives/': {
      id: '/_kit/primitives/'
      path: '/primitives'
      fullPath: '/primitives/'
      preLoaderRoute: typeof KitPrimitivesIndexRouteImport
      parentRoute: typeof KitRoute
    }
    '/_kit/primitives/$id': {
      id: '/_kit/primitives/$id'
      path: '/primitives/$id'
      fullPath: '/primitives/$id'
      preLoaderRoute: typeof KitPrimitivesIdRouteImport
      parentRoute: typeof KitRoute
    }
  }
}

interface KitRouteChildren {
  KitTokensRoute: typeof KitTokensRoute
  KitIndexRoute: typeof KitIndexRoute
  KitComponentsIdRoute: typeof KitComponentsIdRoute
  KitFeaturesIdRoute: typeof KitFeaturesIdRoute
  KitPagesSlugRoute: typeof KitPagesSlugRoute
  KitPatternsIdRoute: typeof KitPatternsIdRoute
  KitPrimitivesIdRoute: typeof KitPrimitivesIdRoute
  KitComponentsIndexRoute: typeof KitComponentsIndexRoute
  KitFeaturesIndexRoute: typeof KitFeaturesIndexRoute
  KitPagesIndexRoute: typeof KitPagesIndexRoute
  KitPatternsIndexRoute: typeof KitPatternsIndexRoute
  KitPrimitivesIndexRoute: typeof KitPrimitivesIndexRoute
}

const KitRouteChildren: KitRouteChildren = {
  KitTokensRoute: KitTokensRoute,
  KitIndexRoute: KitIndexRoute,
  KitComponentsIdRoute: KitComponentsIdRoute,
  KitFeaturesIdRoute: KitFeaturesIdRoute,
  KitPagesSlugRoute: KitPagesSlugRoute,
  KitPatternsIdRoute: KitPatternsIdRoute,
  KitPrimitivesIdRoute: KitPrimitivesIdRoute,
  KitComponentsIndexRoute: KitComponentsIndexRoute,
  KitFeaturesIndexRoute: KitFeaturesIndexRoute,
  KitPagesIndexRoute: KitPagesIndexRoute,
  KitPatternsIndexRoute: KitPatternsIndexRoute,
  KitPrimitivesIndexRoute: KitPrimitivesIndexRoute,
}

const KitRouteWithChildren = KitRoute._addFileChildren(KitRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  KitRoute: KitRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
