export type ProductComponent = {
  id: string;
  name: string;
  group: string;
  description: string;
  usedOn: string[];
  primitives: string[];
};

export const componentGroups = [
  "Chrome",
  "Dashboard",
  "Metrics",
  "Charts",
  "People",
  "Tables",
  "Work",
  "Field",
] as const;

export const productComponents: ProductComponent[] = [
  {
    id: "side-nav",
    name: "Side nav",
    group: "Chrome",
    description: "252px product rail. Group labels, the active item, and the ambassador footer.",
    usedOn: ["Every page"],
    primitives: ["Typography", "Avatar"],
  },
  {
    id: "top-bar",
    name: "Top bar",
    group: "Chrome",
    description: "Page title, people search, language, notifications, and the account avatar.",
    usedOn: ["Every page"],
    primitives: ["Typography", "TextField", "IconButton", "Avatar"],
  },
  {
    id: "page-header",
    name: "Page header",
    group: "Chrome",
    description: "Title, one-line context, and the page actions (Ask Plexi, period, primary button).",
    usedOn: ["Dashboard", "My business", "Contest", "Pulse Check", "Geography"],
    primitives: ["Typography", "Button", "Select"],
  },
  {
    id: "plexi-bar",
    name: "PleXi bar",
    group: "Chrome",
    description: "Pinned assistant along the bottom of the dashboard. Prompt field plus Ask.",
    usedOn: ["Dashboard"],
    primitives: ["Paper", "TextField", "Button", "Avatar"],
  },
  {
    id: "daily-briefing",
    name: "Daily briefing",
    group: "Dashboard",
    description: "Morning card. Eyebrow, headline, and the one thing to do before the team table.",
    usedOn: ["Dashboard"],
    primitives: ["Card", "Typography", "Chip"],
  },
  {
    id: "coach-action",
    name: "Coach action",
    group: "Dashboard",
    description: "One ambassador row inside the briefing: message, primary actions, and pleX-Ray.",
    usedOn: ["Dashboard"],
    primitives: ["Avatar", "Typography", "Button", "IconButton", "Chip"],
  },
  {
    id: "contest-summary",
    name: "Contest summary",
    group: "Dashboard",
    description: "Dashboard contest card. Date range, four KPIs, qualification bar, and View contest.",
    usedOn: ["Dashboard", "Contest"],
    primitives: ["Card", "Typography", "Chip", "LinearProgress", "Button"],
  },
  {
    id: "pulse-widget",
    name: "Pulse Check widget",
    group: "Dashboard",
    description: "Compact forecast on the home page. Scenario select, one PV figure, month segments.",
    usedOn: ["Dashboard"],
    primitives: ["Card", "Select", "Typography", "LinearProgress"],
  },
  {
    id: "team-growth",
    name: "Team growth",
    group: "Dashboard",
    description: "Section header plus the sortable growth table used under the home charts.",
    usedOn: ["Dashboard"],
    primitives: ["Typography", "Button", "Table", "Chip", "Avatar"],
  },
  {
    id: "kpi-stat",
    name: "KPI stat",
    group: "Metrics",
    description: "Single measure. Label, figure, and a signed delta. The atom inside every strip.",
    usedOn: ["Dashboard", "My business", "Contest", "Pulse Check", "Geography", "Points & rank"],
    primitives: ["Paper", "Typography"],
  },
  {
    id: "kpi-strip",
    name: "KPI strip",
    group: "Metrics",
    description: "A row of KPI stats. My business uses six. Contest and Pulse Check use four.",
    usedOn: ["My business", "Contest", "Pulse Check", "Geography"],
    primitives: ["Paper", "Typography"],
  },
  {
    id: "progress-meter",
    name: "Progress meter",
    group: "Metrics",
    description: "Label, value, and a determinate bar. Rank pace, qualification, and course completion.",
    usedOn: ["Contest", "Points & rank", "Plexus U", "pleX-Ray"],
    primitives: ["Typography", "LinearProgress"],
  },
  {
    id: "segmented-meter",
    name: "Segmented meter",
    group: "Metrics",
    description: "Month ticks colored by threshold. The Pulse Check bar, not a single LinearProgress.",
    usedOn: ["Dashboard", "Pulse Check"],
    primitives: ["Typography", "Box"],
  },
  {
    id: "rank-chip",
    name: "Rank chip",
    group: "Metrics",
    description: "Outlined secondary chip for Diamond, Emerald, Gold, Silver. Quiet, never filled.",
    usedOn: ["Dashboard", "Contest", "CRM", "Genealogy", "Recognition"],
    primitives: ["Chip"],
  },
  {
    id: "status-chip",
    name: "Status chip",
    group: "Metrics",
    description: "Filled status. On track, watch, at risk, new, live. Color is the only signal.",
    usedOn: ["Dashboard", "CRM", "Playbook", "Live"],
    primitives: ["Chip"],
  },
  {
    id: "period-chart",
    name: "Period comparison",
    group: "Charts",
    description: "Two-series line chart. This period against the prior period, by month.",
    usedOn: ["My business"],
    primitives: ["Paper", "Typography", "Select"],
  },
  {
    id: "forecast-chart",
    name: "Volume forecast",
    group: "Charts",
    description: "Line of team PV with a reference line for the rank or contest threshold.",
    usedOn: ["Pulse Check"],
    primitives: ["Paper", "Typography"],
  },
  {
    id: "donut-chart",
    name: "Distribution donut",
    group: "Charts",
    description: "Share of volume by customer type. Donut plus a legend, not a pie with labels on the slices.",
    usedOn: ["My business"],
    primitives: ["Paper", "Typography"],
  },
  {
    id: "region-bars",
    name: "Region bars",
    group: "Charts",
    description: "Horizontal bars for enrollments or PV by region. Geography’s primary chart.",
    usedOn: ["Geography"],
    primitives: ["Paper", "Typography", "LinearProgress"],
  },
  {
    id: "person-cell",
    name: "Person cell",
    group: "People",
    description: "Avatar, name, and a secondary line (rank, PV, enrolled). The first column of every people table.",
    usedOn: ["Dashboard", "Contest", "CRM", "Inbox", "Recognition"],
    primitives: ["Avatar", "Typography", "Chip"],
  },
  {
    id: "tree-node",
    name: "Tree node",
    group: "People",
    description: "Genealogy card. Name, rank chip, PV, and a count of the leg underneath.",
    usedOn: ["Genealogy"],
    primitives: ["Paper", "Avatar", "Typography", "Chip"],
  },
  {
    id: "feed-item",
    name: "Recognition item",
    group: "People",
    description: "One moment in the recognition feed. Who, what changed, and when.",
    usedOn: ["Recognition"],
    primitives: ["Paper", "Avatar", "Typography", "Chip"],
  },
  {
    id: "growth-table",
    name: "Growth table",
    group: "Tables",
    description: "Sortable team table. Person, rank, PV, change, new enrollments, status, pleX-Ray.",
    usedOn: ["Dashboard"],
    primitives: ["Table", "TableSortLabel", "Avatar", "Chip", "Button"],
  },
  {
    id: "leaderboard",
    name: "Leaderboard",
    group: "Tables",
    description: "Contest standings. Place, person, both PV columns, qualification meter, row actions.",
    usedOn: ["Contest"],
    primitives: ["Table", "Avatar", "Chip", "LinearProgress", "IconButton"],
  },
  {
    id: "orders-table",
    name: "Orders table",
    group: "Tables",
    description: "Recent orders. Date, customer, type, amount, status.",
    usedOn: ["My business"],
    primitives: ["Table", "Chip", "Typography"],
  },
  {
    id: "crm-table",
    name: "CRM table",
    group: "Tables",
    description: "People grid. Status, rank, PV, last order, owner, and the row menu.",
    usedOn: ["CRM"],
    primitives: ["Table", "Avatar", "Chip", "IconButton"],
  },
  {
    id: "scenario-table",
    name: "Scenario table",
    group: "Tables",
    description: "Pulse Check cases. Name, assumed PV, gap to threshold, and whether it qualifies.",
    usedOn: ["Pulse Check"],
    primitives: ["Table", "Chip", "Typography"],
  },
  {
    id: "action-list",
    name: "Action list",
    group: "Work",
    description: "Ordered follow-ups. Owner, why it matters, due label, and a single next action.",
    usedOn: ["Playbook", "Pulse Check"],
    primitives: ["Paper", "Avatar", "Typography", "Button", "Chip"],
  },
  {
    id: "message-list",
    name: "Message list",
    group: "Work",
    description: "Inbox rail. Avatar, name, preview, time, and the unread marker.",
    usedOn: ["Inbox"],
    primitives: ["List", "Avatar", "Typography"],
  },
  {
    id: "thread",
    name: "Conversation",
    group: "Work",
    description: "The open thread. Incoming and outgoing bubbles plus the reply field.",
    usedOn: ["Inbox"],
    primitives: ["Paper", "Typography", "TextField", "Button"],
  },
  {
    id: "saved-views",
    name: "Saved views",
    group: "Work",
    description: "CRM view tabs. One selected, the rest text. Counts sit in the label.",
    usedOn: ["CRM"],
    primitives: ["Tabs", "Chip"],
  },
  {
    id: "filter-bar",
    name: "Filter bar",
    group: "Work",
    description: "Search plus the small selects used above contest, CRM, and geography tables.",
    usedOn: ["Contest", "CRM", "Geography", "Playbook"],
    primitives: ["TextField", "Select", "Button"],
  },
  {
    id: "segment-control",
    name: "Segment control",
    group: "Work",
    description: "Exclusive toggle for Overview / Scenarios / Actions and the geography measures.",
    usedOn: ["Pulse Check", "Geography", "Points & rank"],
    primitives: ["ToggleButton"],
  },
  {
    id: "profile-form",
    name: "Profile form",
    group: "Field",
    description: "Account fields. Name, email, rank (read-only), and the save action.",
    usedOn: ["My account"],
    primitives: ["TextField", "Typography", "Button"],
  },
  {
    id: "subscription-row",
    name: "Subscription row",
    group: "Field",
    description: "One add-on. Name, cadence, price, and Add or Manage.",
    usedOn: ["My account"],
    primitives: ["Paper", "Typography", "Button", "Chip"],
  },
  {
    id: "share-card",
    name: "Share card",
    group: "Field",
    description: "Link field, copy, and the QR action. Sharing Plexus.",
    usedOn: ["Sharing"],
    primitives: ["Paper", "TextField", "Button", "Typography"],
  },
  {
    id: "journey-stage",
    name: "Journey stage",
    group: "Field",
    description: "One step on 360 Journey. Index, name, and done / now / next.",
    usedOn: ["360 Journey"],
    primitives: ["Paper", "Typography", "Chip", "LinearProgress"],
  },
  {
    id: "course-card",
    name: "Course card",
    group: "Field",
    description: "Plexus U course. Title, lesson count, and completion.",
    usedOn: ["Plexus U"],
    primitives: ["Card", "Typography", "LinearProgress", "Chip"],
  },
  {
    id: "hub-row",
    name: "Hub row",
    group: "Field",
    description: "One hub document. Id, title, updated time, and a state chip.",
    usedOn: ["Plexus Hub"],
    primitives: ["Paper", "Typography", "Chip"],
  },
  {
    id: "live-session",
    name: "Live session",
    group: "Field",
    description: "Plexus Live card. Live chip, title, start time, and Join.",
    usedOn: ["Plexus Live"],
    primitives: ["Paper", "Chip", "Typography", "Button"],
  },
  {
    id: "kickoff-agenda",
    name: "Kickoff agenda",
    group: "Field",
    description: "Numbered agenda for monthly kickoff. Time, item, owner.",
    usedOn: ["Monthly kickoff"],
    primitives: ["Typography", "Chip"],
  },
  {
    id: "notice-banner",
    name: "Notice banner",
    group: "Field",
    description: "Hub and page alerts. A tinted paper, a title, and a dismiss.",
    usedOn: ["Plexus Hub"],
    primitives: ["Paper", "Typography", "IconButton"],
  },
];

export const primitiveUsers = (name: string) => productComponents.filter((item) => item.primitives.includes(name));
